$(document).ready(function(){
  $("#but1").click(function(){
    $("#tab1").toggle();
  });
});
$(document).ready(function(){
  $("#but2").click(function(){
    $("#tab2").toggle();
  });
});
$(document).ready(function(){
  $("#but3").click(function(){
    $("#tab3").toggle();
  });
});
$(document).ready(function(){
  $("#but4").click(function(){
    $("#tab4").toggle();
  });
});
